# aarch has issues with newer GCC
c_compiler_version:             # [aarch64]
  - 11                          # [aarch64]
  - 11                          # [aarch64]
cxx_compiler_version:           # [aarch64]
  - 11                          # [aarch64]
  - 11                          # [aarch64]

github_actions_labels:                              # [unix]
- ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-lg   # [linux]
- cirun-macos-m4-large                              # [osx]
microarch_level:
- 1
# hmaarrfk -- temporary, uncomment during actual build
- 3   # [linux and x86_64]
